**Importing MNIST dataset from keras and reshaping to feed to SVM**

In [1]:
from keras.datasets import mnist
from sklearn import model_selection,preprocessing,svm

(inp_train,tar_train),(inp_test,tar_test)=mnist.load_data()

inp_train=inp_train.reshape(60000,784)
inp_test=inp_test.reshape(10000,784)



Using TensorFlow backend.


**Visualizing the shape of training and testing dataset**

In [2]:
(inp_train.shape,tar_train.shape),(inp_test.shape,tar_test.shape)

(((60000, 784), (60000,)), ((10000, 784), (10000,)))

**Scaling the data to help SVM converge**

In [0]:
inp_train=preprocessing.scale(inp_train)
inp_test=preprocessing.scale(inp_test)


**Building a SVM Linear Classifier with default parameter C=1.0**

In [4]:
svm_linear = svm.SVC(kernel='linear')
svm_linear.fit(inp_train, tar_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

**Predicting and Calculating Accuracy**

In [0]:
predictions = svm_linear.predict(inp_test)

In [6]:
from sklearn import metrics

confusion_matrix = metrics.confusion_matrix(tar_test,predictions)
print(confusion_matrix,"\n")
print('Accuracy=',metrics.accuracy_score(tar_test,predictions))

[[ 953    0    6    2    1    8    6    2    1    1]
 [   0 1118    7    2    0    1    2    1    4    0]
 [   9   12  956   11    9    4    5    5   18    3]
 [   7    1   15  940    0   17    1    6   19    4]
 [   3    2   18    1  927    0    3    6    3   19]
 [   7    6    7   40    5  791   12    1   20    3]
 [  14    3   17    1    9   19  892    0    3    0]
 [   2    8   23   14   11    2    0  945    2   21]
 [  11    7   10   29    8   23    8    6  860   12]
 [   9    7    6   11   38    5    0   23   12  898]] 

Accuracy= 0.928


In [7]:
print("Displaying Classification Report:\n",metrics.classification_report(y_true=tar_test, y_pred=predictions))

Displaying Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.97      0.96       980
           1       0.96      0.99      0.97      1135
           2       0.90      0.93      0.91      1032
           3       0.89      0.93      0.91      1010
           4       0.92      0.94      0.93       982
           5       0.91      0.89      0.90       892
           6       0.96      0.93      0.95       958
           7       0.95      0.92      0.93      1028
           8       0.91      0.88      0.90       974
           9       0.93      0.89      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000



**Selecting hyperparameter 'C' with 3-fold cross-validation**

In [4]:
from sklearn.model_selection import cross_val_score
import numpy as np

mean_scores=[]
for c in [0.5,1,2,3,10]:

  lsvm = svm.SVC(kernel='linear', C=c)
  cv_scores = cross_val_score(lsvm, inp_train, tar_train, cv=3)
  print('For C=',c," Cross-Validation Scores: ",cv_scores)
  mean_scores.append(np.mean(cv_scores))


For C= 0.5  Cross-Validation Scores:  [0.9187  0.91935 0.921  ]
For C= 1  Cross-Validation Scores:  [0.9154 0.9172 0.9185]
For C= 2  Cross-Validation Scores:  [0.9135  0.9161  0.91545]
For C= 3  Cross-Validation Scores:  [0.9133 0.9147 0.9154]
For C= 10  Cross-Validation Scores:  [0.91095 0.91305 0.913  ]


In [5]:
i=0
for c in [0.5,1,2,3,10]:
  print('For C=',c," Mean Cross-Validation Score: ",mean_scores[i])
  i+=1

For C= 0.5  Mean Cross-Validation Score:  0.9196833333333334
For C= 1  Mean Cross-Validation Score:  0.9170333333333334
For C= 2  Mean Cross-Validation Score:  0.9150166666666667
For C= 3  Mean Cross-Validation Score:  0.9144666666666666
For C= 10  Mean Cross-Validation Score:  0.9123333333333333
